# Log properties
logging:
  level.org.springframework: INFO
  level.com.dbg: DEBUG
  level.org.springframework.data.mongodb.core.MongoTemplate: DEBUG
# Spring properties
spring:
  application:
    name: atquiz
# MONGODB (MongoProperties)
  data:
    mongodb:
      uri: mongodb://localhost/quiz
# HTTP Server
server:
  port: 8081